apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: techtrends-prod
    namespace: argocd
spec:
    destination:
        namespace: default
        server: https://kubernetes.default.svc
    project: default
    source:
        helm:
            valueFiles:
                - values-prod.yaml
        path: helm
        repoURL: https://github.com/arfat-mateen/TechTrends_Cloud_Native_Application_Architecture
        targetRevision: HEAD
    syncPolicy: {}
